sudo: required
dist: trusty

language: node_js

node_js:
  - 6

cache:
  directories:
    - $HOME/.npm

install:
  - yarn install --ignore-engines

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

matrix:
  include:
  - services:
      - docker

  - before_script:
      - ng build --prod --aot --build-optimizer

  - script:
      - ng test --single-run --code-coverage --reporters=coverage-istanbul

  - script:
      - ng lint --format=stylish
      - docker build -t loklak_server .

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash ./pr_deploy.sh
  - bash ./deploy.sh

# safelist
branches:
  only:
  - development
